backend:
  name: git-gateway
  branch: development # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "changelog" # Used in routes, e.g., /admin/collections/blog

    label: "Changelogs" # Used in the UI

    folder: "src/content/changelog/" # The path to the folder where the documents are stored

    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: true
        widget: "datetime"
        default: ""

      - label: "Version"
        name: "version"
        required: true
        widget: "string"

      - label: "Changelog Type"
        name: "changelog"
        required: true
        widget: inline-select
        multiple: true
        options: ["API", "Cloud Manager"]

      - label: "Content"
        name: "body"
        widget: "markdown"
        default: "<!-- API changelog requirements - delete this before merging -->

          - Replace all instances of X.X.X in the frontmatter with the appropriate API spec.

          - Replace all instances of 2019-01-01 with the production release date for the API.

          - All items in the changelog should mention which endpoints are affected.

          - For changes and bugfixes, describe the previous behavior AND the new behavior.


          <!-- Where to put things - delete this before merging -->

          Some heuristics for which heading to put API reference updates under:


          *Added*

            - New endpoints.

            - New fields in the request or a response of an existing endpoint.


          *Changed*

            - Changes in the behavior of an existing endpoing, when the previous behavior was working as it was designed. In other words, non-bugfix changes.


          *Fixes*

            - Bugfixes: Changes to the behavior of an endpoint, where the previous behavior was not working as intended/expected/documented.


          <!-- Sample syntax - delete this before merging -->


            - References to an endpoint should be in this format: `the Endpoint Name ([VERB /path/to/endpoint/{endpointVariable}](https://developers.linode.com/api/docs/v4/{endpoint}/{#endpointVariable})) endpoint`
              *Example*: `the Clone Linode ([POST /linode/instances/{linodeId}/clone](https://developers.linode.com/api/v4/linode-instances-linode-id-clone/#post)) endpoint`


          <!-- Fill these sections out: -->


          ### Added


          ### Changed


          ### Fixed"
        required: true
